Repository tushargupta1504/Medical-Website, pull requests merged in 2024-10, with the labels that each got.

#26 Made the navbar links work
  index.html
Labels: gssoc-ext 24

#38 added the hover animation to the image.
  index.html
  style.css
Labels: gssoc-ext 24

#81 enhanced Contact form issue #17
  index.html
Labels: gssoc-ext 24, hacktoberfest

#88 Update Readme.md
  Readme.md
Labels: good first issue, gssoc-ext 24, hacktoberfest, hacktoberfest-accepted

#130 Increased font size of the card and text is more readable now.
  index.html
Labels: hacktoberfest

#126 fix: page navigation from nearby solved
  nearby.html
Labels: gssoc-ext 24, hacktoberfest

#123 enhancement: increase text size for class card-body
  style.css
Labels: gssoc-ext 24

#137 Add photoswipe on Gallery and Zoom In animation on hover Gallery Image
  index.html
  style.css
Labels: documentation, gssoc-ext 24

#150 adding hover and making basic ui changes #134
  style.css
Labels: good first issue, gssoc-ext 24, hacktoberfest, level - 2

#158 add functionality to submit button #51
  index.html
Labels: gssoc-ext 24, hacktoberfest

#203 added animation on scroll
  index.html
Labels: enhancement, good first issue, gssoc-ext 24, hacktoberfest

#154 add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  Code of Conduct.md
  code of conduct.md
Labels: gssoc-ext 24, hacktoberfest

#180 Delete unnecessary files
  bootstrap-5.3.2-dist.zip
  bootstrap.bundle.min.js
  bootstrap.css
Labels: gssoc-ext 24, hacktoberfest

#220 update in send message button position
  index.html
Labels: enhancement, gssoc-ext 24, hacktoberfest, level1

#267 made changes on forms and validated the form before submission and fi…
  index.html
  nearby.html
Labels: enhancement, gssoc-ext, hacktoberfest, level1

#249 Updated Service Section
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level1

#242 Efrata-Swasthya-Medical
  appointment.html
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level2

#266 Added Blog section and updated contact section
  blog.css
  blog.html
  img/Blog_diet.jpg
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level3

#285 [DOCS] UPDATE README #226
  Readme.md
Labels: gssoc-ext, level1

#316 Fixed UI at header
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level2

#297 Improving visual appeal
  script3.js
  style.css
Labels: gssoc-ext, hacktoberfest, level1

#484 the letters are more visible in darkmode #483
  index.js
  style.css
Labels: enhancement, gssoc-ext, hacktoberfest, level1

#518 contact us is made visible in darkmode
  index.html
  index.js
  style.css
Labels: gssoc-ext, hacktoberfest, level1

#534 i have changed the footer section
  MedicalBot/favicon.svg
  MedicalBot/style.css
  index.html
Labels: enhancement, gssoc-ext, hacktoberfest, level1

#527 Created User generated content and reviews page
  index.html
  reviews.html
Labels: gssoc-ext, hacktoberfest, level1

#572 Add a ChatBot Assistant done ! #561
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level3

#663 Update Readme.md
  Readme.md
Labels: enhancement, hacktoberfest, level2
