Repository tushargupta1504/Medical-Website, pull requests merged in 2024-11, with the labels that each got.

#700 Change in UI #280
  index.html
Labels: gssoc-ext, hacktoberfest, level2

#702 Revert "testingCommit message for submodule changes"
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#684 Update index.html
  index.html
Labels: gssoc-ext, level3
